import { useState, useCallback } from "react";
import jsPDF from "jspdf";
import type { ModernizeResponse } from "../types";

interface Props {
  response: ModernizeResponse;
  sourceLang: string;
  targetLang: string;
}

export default function PDFExport({ response, sourceLang, targetLang }: Props) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = useCallback(() => {
    setGenerating(true);

    try {
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 15;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      const addText = (text: string, size: number, bold = false, color: [number, number, number] = [30, 30, 30]) => {
        doc.setFontSize(size);
        doc.setFont("helvetica", bold ? "bold" : "normal");
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(text, maxWidth);
        for (const line of lines) {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.text(line, margin, y);
          y += size * 0.5;
        }
        y += 2;
      };

      const addSeparator = () => {
        if (y > 265) { doc.addPage(); y = 20; }
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;
      };

      // Header
      addText("LegacyLift — Migration Report", 20, true, [50, 50, 50]);
      addText(`Generated: ${new Date().toLocaleString()}`, 9, false, [120, 120, 120]);
      y += 4;

      addSeparator();

      // Summary
      addText("Migration Summary", 14, true);
      addText(`Source: ${sourceLang.toUpperCase()}  →  Target: ${targetLang.toUpperCase()}`, 10);
      addText(`Confidence Score: ${Math.round(response.confidence_score * 100)}%`, 10);

      if (response.complexity) {
        const c = response.complexity;
        addText(`Complexity: ${c.complexity_score}/10 (${c.difficulty})`, 10);
        addText(`Estimated Manual Effort: ${c.estimated_effort_hours} hours`, 10);
        addText(`Code Lines: ${c.code_lines} | Functions: ${c.num_functions} | Classes: ${c.num_classes}`, 10);
      }

      y += 2;
      addSeparator();

      // Change summary
      if (response.change_summary) {
        addText("Change Summary", 14, true);
        addText(response.change_summary, 9);
        y += 2;
        addSeparator();
      }

      // Documentation
      if (response.documentation) {
        addText("Documentation", 14, true);
        const docText = response.documentation.replace(/[#*`]/g, "").substring(0, 3000);
        addText(docText, 8);
        y += 2;
        addSeparator();
      }

      // Test results
      if (response.test_results?.length > 0) {
        addText("Test Results", 14, true);
        const passed = response.test_results.filter((r) => r.passed === true).length;
        const total = response.test_results.length;
        addText(`${passed} / ${total} tests passed`, 10, false, passed === total ? [22, 163, 74] : [220, 38, 38]);
        y += 2;

        for (const result of response.test_results) {
          const icon = result.passed === true ? "PASS" : result.passed === false ? "FAIL" : "SKIP";
          const color: [number, number, number] = result.passed === true ? [22, 163, 74] : result.passed === false ? [220, 38, 38] : [150, 150, 150];
          addText(`  [${icon}] ${result.name}${result.error ? ` — ${result.error}` : ""}`, 8, false, color);
        }
        addSeparator();
      }

      // Original code (truncated)
      addText("Original Code (preview)", 14, true);
      doc.setFont("courier", "normal");
      const origLines = response.original_code.substring(0, 2000).split("\n");
      for (const line of origLines.slice(0, 40)) {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(7);
        doc.text(line.substring(0, 120), margin, y);
        y += 3;
      }
      doc.setFont("helvetica", "normal");
      y += 2;
      addSeparator();

      // Modernized code (truncated)
      addText("Modernized Code (preview)", 14, true);
      doc.setFont("courier", "normal");
      const modLines = response.modernized_code.substring(0, 2000).split("\n");
      for (const line of modLines.slice(0, 40)) {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.setFontSize(7);
        doc.text(line.substring(0, 120), margin, y);
        y += 3;
      }

      // Footer on last page
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by LegacyLift", margin, 285);

      doc.save(`legacylift-report-${Date.now()}.pdf`);
    } finally {
      setGenerating(false);
    }
  }, [response, sourceLang, targetLang]);

  return (
    <button
      onClick={generatePDF}
      disabled={generating}
      className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
        generating
          ? "bg-gray-200 dark:bg-gray-700 text-gray-400 cursor-wait"
          : "bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300"
      }`}
    >
      {generating ? "Generating..." : "Export PDF"}
    </button>
  );
}
